openrewrite/rewrite-jenkins

src/main/java/org/openrewrite/jenkins/AddPluginsBom.java
src/test/java/org/openrewrite/jenkins/AddPluginsBomTest.java

The `AddPluginsBom` recipe has two new features:
* Minimizes ordering changes and comment movement by changing the first outdated BOM instead of removing and adding
* Always updates an outdated BOM if present, even if there are no included plugins
Spent some time triaging why a BOM was left out of sync with a `jenkins.version` property after running a recipe. I think this better aligns with expected behavior.
I also considered removing an unused BOM, but then we'd have a recipe called AddPluginsBom that may only remove a BOM. I thought this would be more confusing than updating.
Using PR so release notes are easy to generate.

`AddPluginsBom`: Change First Outdated BOM to Minimize Ordering Changes

---

src/main/resources/META-INF/rewrite/hudson-migrations.yml
src/test/java/org/openrewrite/jenkins/migrate/hudson/UtilGetPastTimeStringToTimeSpanStringTest.java

Introduced a new rule to automatically move from a deprecated method to a preferred one.
Starting to implement rewrite equivalents of the jackpot rules mentioned in Issue #6.

Add `hudson.Util.getPastTimeString` Migration Rule

---

src/main/resources/META-INF/rewrite/jsr-305.yml
src/test/java/org/openrewrite/jenkins/JavaxAnnotationsToSpotBugsTest.java

`org.openrewrite.java.OrderImports` removed from `org.openrewrite.jenkins.JavaxAnnotationsToSpotbugs` recipe.
Creates too many unrelated changes. This is sometimes viewed as noise, adding friction to potential merges.
If there is a way to order imports only in already-changed files, that would be preferred.
Fixes #10.

Remove `OrderImports` from `JavaxAnnotationsToSpotbugs`

---

src/main/resources/META-INF/rewrite/rewrite.yml

Running the ModernizePlugin recipe will now set the minimum `jenkins.version` to `2.387.3`.
As of https://github.com/jenkinsci/bom/pull/2218 bom-2.375.x is no longer being published.

Bump Modernized `jenkins.version` to 2.387.3

---

src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
src/main/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGenerator.java
src/main/java/org/openrewrite/jenkins/github/TeamNameGenerator.java
src/main/java/org/openrewrite/jenkins/github/TeamNameInput.java
src/main/java/org/openrewrite/jenkins/github/package-info.java
src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java
src/test/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGeneratorTest.java

A new recipe has been introduced.
Closes #19.
The style-matching implementation is done in-recipe, there may be a better way to do this.
@timtebeek @basil

Introduce AddTeamToCodeowners Recipe

---

src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java

* Generate new file with a trailing space so it looks nicer in the git diff
* Ensure only the .github/CODEOWNERS file is modified
* Match existing declaration of team even if it includes trailing spaces
Followup to #19 to correct some issues after initial run.
@timtebeek

CODEOWNERS Enhancements

---

src/main/resources/META-INF/rewrite/rewrite.yml

Fixes #27 by removing the dependency on `symbol-annotation`. We do this only for the `org.openrewrite.jenkins.ModernizePlugin` recipe and not the `org.openrewrite.jenkins.ModernizePluginForJava8` recipe because the latter only bumps the core version up to 2.346.3, and a recent version of `symbol-annotation` is only delivered by core as of 2.349. We tested this by running `org.openrewrite.jenkins.ModernizePlugin` against jenkinsci/artifact-repository-parameter-plugin@b0a0a4e and verifying that the `symbol-annotation` dependency was successfully removed. We did not add any test coverage in this repository because `org.openrewrite.java.RemoveDependency` is upstream functionality that is already tested upstream, and similar usages in this repository (e.g., the usage of …

Remove dependency on `symbol-annotation`

---

src/main/resources/META-INF/rewrite/rewrite.yml

Fixes #26 by removing any usages of Animal Sniffer annotations. The only annotation that exists in Animal Sniffer is `org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement`, so that is the only annotation we remove. We do this only for the `org.openrewrite.jenkins.ModernizePlugin` recipe and not the `org.openrewrite.jenkins.ModernizePluginForJava8` recipe because Animal Sniffer is still used in Java 8. We tested this by running `org.openrewrite.jenkins.ModernizePlugin` against jenkinsci/active-directory-plugin@c493ebc and verifying that the Animal Sniffer annotation and its import were successfully removed. We did not add any test coverage in this repository because `org.openrewrite.java.RemoveAnnotation` is upstream functionality that is already tested upstream, and similar usages in …

Remove usages of Animal Sniffer

---

build.gradle.kts
src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
src/main/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGenerator.java
src/main/java/org/openrewrite/jenkins/github/InMemoryTeamNameValidator.java
src/main/java/org/openrewrite/jenkins/github/TeamNameValidator.java
src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersScannedTest.java
src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java
src/test/java/org/openrewrite/jenkins/github/ArtifactIdTeamNameGeneratorTest.java
src/test/java/org/openrewrite/jenkins/github/InMemoryTeamNameValidatorTest.java

A `-plugin` suffix is now removed from an `artifactId` before generating the team name.
Team names are validated with a simple in-memory implementation.
Generated a few PRs that had invalid team names.
Are there preferred ways for pulling the list of valid team names? I could make a GitHub API call, but I suspect I'd be rate-limited. I'm considering regularly updating a list that is shipped with this repo, or publishing a separate jar regularly that contains known team names. The implementation here works for stopping repeat mistakes.
I attempted to introduce a secondary constructor for the recipe so I could inject a mock validator for testing. This ran into serialization errors. Is there a preferred way to mock dependencies for recipes?
@timtebeek

CODEOWNERS Validation

---

README.md

Added example and link to docs for running without modifying build.
Closes #44.

Add Quick Start to README for `mvn` Runs

---

README.md

Use org.openrewrite.jenkins.github.AddTeamToCodeowners in the example since the lead-in text says that and that is a more likely needed refactoring than the deprecated API replacement.
Documentation improvement for the README in the Jenkins recipe so that the instruction that is provided 
Allows me to experiment with a single recipe from the command line.
N/A
N/A
Workaround is to use the command myself without updating the documentation.
N/A

Match executed command to documentation

---

src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java
src/test/java/org/openrewrite/jenkins/github/AddTeamToCodeownersTest.java

Before the file is generated in AddTeamToCodeowners, we verify the team name is valid.
Closes #49. Prevents generating unexpected changes.

Skip CODEOWNERS generation for invalid teams

---

src/main/resources/META-INF/rewrite/rewrite.yml
src/test/java/org/openrewrite/jenkins/ModernizeJenkinsfileTest.java

The default archetype has changed:  https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile
I have just changed the Jenkinsfile template, as it has recently changed in the Jenkins official archetype repo.
I've been doing that kind of work by hand lately on quite a few plugins, and think it could be automated.
- ~~I've added unit tests to cover both positive and negative cases~~
- ~~I've added the license header to any new files through `./gradlew licenseFormat`~~

chore(dependencies): Move to JDK21

---

src/main/resources/META-INF/rewrite/rewrite.yml

- Raised baseline to 2.401.3
- Added `javax.inject` -> `jakarta.inject` package change
- Baseline is [current recommended version](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions)
- `jakarta.inject` is preferred and supported since 2.401.2 (jenkinsci/jenkins#8121)
Introducing a separate rule for the package change that is only active when the baseline version is `>= 2.401.2`.

Bump minimum Jenkins baseline to 2.401.3

---

src/main/java/org/openrewrite/jenkins/AddPluginsBom.java
src/test/java/org/openrewrite/jenkins/AddPluginsBomTest.java

AddPluginsBom recipe now supports properties declared after the bom.
Several plugins have this ordering defined. It worked in the previous ScanningRecipe implementation, this restores the behavior with a regular Recipe.
Recipe causing another cycle, but this seems simpler.

Make AddPluginsBom Order Independent

---

src/main/resources/META-INF/rewrite/rewrite.yml

- Raised baseline Jenkins version to 2.426.3
- Baseline is [current recommended version](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) as of https://github.com/jenkins-infra/jenkins.io/commit/6415adcc6d4e1f9afc5d60ad974fb26e64eba726
#53 is most recent similar change.

Raise minimum Jenkins baseline version to 2.426.3

---

src/main/java/org/openrewrite/jenkins/UpgradeVersionProperty.java
src/test/java/org/openrewrite/jenkins/UpgradeVersionPropertyTest.java

Archetype changed recently to use `jenkins.baseline` that is also used to resolve the bom.
This should have been fixed on https://github.com/openrewrite/rewrite/pull/4404#issuecomment-2408072231
But there is one other case on `UpgradeVersionProperty` that prevent moving from one version to another
@sghill @timtebeek @sambsnyd
@gounthar for info
Confirmed it worked by adding 2 new tests and ensuring the old format without the `jenkins.baseline` continue to work

Handle jenkins.baseline property on UpgradeVersionProperty

---

src/main/java/org/openrewrite/jenkins/AddPluginsBom.java
src/main/java/org/openrewrite/jenkins/Jenkins.java
src/test/java/org/openrewrite/jenkins/AddPluginsBomTest.java
src/test/java/org/openrewrite/jenkins/JenkinsTest.java

Handle presence of `jenkins.baseline` on artifact ID. 
Doesn't perform migration by adding the `jenkins.baseline` property which should be done at some point
Jenkins changed their archetype to include the `jenkins.baseline` property

Handle jenkins.baseline on AddPluginsPom

---

src/main/java/org/openrewrite/jenkins/github/AddTeamToCodeowners.java

AddTeamToCodeowners didn't work on windows.
I don't have a WIndows environment to confirm but seen on this PR https://github.com/jenkins-infra/plugin-modernizer-tool/pull/518 (added tests for some YAML recipes that uses the `AddTeamToCodeowners`)
The test work well on Linux but fail on Windows
I'm 99% sure it's due to this path comparison and path separator

AddTeamToCodeowners doesn't work in Windows

---

src/main/resources/META-INF/rewrite/rewrite.yml
src/test/java/org/openrewrite/jenkins/ModernizeJenkinsfileTest.java

Parse Jenkinsfile as groovy and missing forkCount
Missing `forkCount`, fix empy line removed by yaml block and parse Jenkinsfile as groovy for tests

Parse Jenkinsfile as groovy and missing forkCount

---

src/main/java/org/openrewrite/jenkins/DisableLocalResolutionForParentPom.java
src/test/java/org/openrewrite/jenkins/DisableLocalResolutionForParentPomTest.java
src/test/java/org/openrewrite/jenkins/ModernizePluginForJava8Test.java

See https://github.com/jenkinsci/archetypes/blob/master/empty-plugin/src/main/resources/archetype-resources/pom.xml#L9
Default formatting of pom (spotless)

Missing space after relativePath

---

src/main/java/org/openrewrite/jenkins/JenkinsfileAsGroovy.java
src/main/resources/META-INF/rewrite/rewrite.yml
src/test/java/org/openrewrite/jenkins/CreateJenkinsfileTest.java

This recipe adds a base Jenkinsfile to any project that doesn't have one created already. It is written in Groovy for a Declarative Pipeline.
Populate a basic template for anyone who wants to migrate to a Jenkinsfile for their pipeline or start out their project with a Jenkinsfile.
@timtebeek 
- [N/A] I've added unit tests to cover both positive and negative cases

Add `CreateJenkinsfile` recipe for a quick declarative base recipe
